#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#bspc monitor HDMI-A-0 -d I
#bspc monitor DisplayPort-1 -d II III IV V VI VII VIII IX X

bspc monitor DisplayPort-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#AutoStart applications
xinput set-prop 12 "libinput Accel Profile Enabled" 0 1 0 &
sxhkd &
picom --config $HOME/.config/picom/picom.conf -b &
/usr/bin/emacs --daemon &
setxkbmap -layout se,se,ru dvorak,, -option ctrl:nocaps,grp:alt_shift_toggle &
/usr/bin/gentoo-pipewire-launcher restart &
/usr/bin/gnome-keyring-daemon &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --all &
xscreensaver &
